version: '3.2'
services:

  angular:
    build: .
    # deploy:
    #   replicas: 2
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure
    ports:
      - '80:80'
